### ISSUE TITLE
Do not use app.run in production.

### ISSUE THREAD

**Issue by laundmo** [archivy/archivy#170]
as [per the flask docs](https://flask.palletsprojects.com/en/1.1.x/deploying/)  and the warning that should be shown when running, you should not use the development server in production which is what `archivy run` will start. 

the development server is very insecure, has a low performance and of generally bad. it should only run when actually developing the app.

**Comment by Uzay-G** [comment]
This is true.

Do you have any solutions for running that wouldn't have to include another dependency like gunicorn?

Otherwise I will document this and suggest ways to run it in production - with links to webserver options.

Ideally there would be a native python dependency with which the `archivy run` could load a secure and performant webserver.

**Comment by Uzay-G** [comment]
We could use gunicorn https://github.com/benoitc/gunicorn/issues/91

**Comment by laundmo** [comment]
i personally use this docker container: https://github.com/tiangolo/meinheld-gunicorn-flask-docker

there is no way to run flask without another dependency. it just doesn't support that. You could see if Quart works with this, its a framework with the same API as flask.
