### ISSUE TITLE
Request: Improve page title in browser

### ISSUE THREAD

**Issue by BrianGilbert** [archivy/archivy#192]
I suggest updating the page title to indicate the location of the note in addition to the note title, by traversing the breadcrumb eg.

![Reading Material - Archivy 2021-02-03 16-33-43](https://user-images.githubusercontent.com/114017/106703084-9b54db80-663d-11eb-89dd-4d440cf92e17.png)

Page title would be something like :
`Reading Material/House/Making - Archivy`

**Comment by Uzay-G** [comment]
I'm not sure how useful this would be, considering the title should already make things pretty distinctive. However, this issue prompted me to add a title for folder viewing, because the title for the folder page was always `home` (https://github.com/archivy/archivy/commit/f1cb25bf7e87f8ceb621e74d3229ef0ea51faeba)
